<?php
/**
 * @file
 * Code for the parrot Splash Image & Slideshow feature.
 */

include_once 'parrot_splash_image.features.inc';

/**
 * Implements of hook_views_api_alter()
 *
 * Adds views templates.
 */
function parrot_splash_image_views_api_alter(&$list) {

  $list['views']['template path'] = drupal_get_path('module', 'parrot_splash_image') . '/templates';

}

/**
 * Implementation of hook_theme().
 */
/*function parrot_splash_image_theme($existing, $type, $theme, $path) {

  $themes['views_view__media_asset_splash'] = array(
    'original hook' => 'views_view',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view',
      'parrot_splash_image_preprocess_views_view__media_asset_splash',
    ),
    'arguments' => array('view_array' => array(), 'view' => NULL),
  );

  return $themes;

}*/

/**
 * Views preprocess function.
 *
 * Adds default css to splash feature.
 */
/*function parrot_splash_image_preprocess_views_view__media_asset_splash(&$variables) {

  $path = drupal_get_path('module', 'parrot_splash_image');

  drupal_add_css($path . '/css/parrot_splash_image.css');

}*/

/**
 * Implements hook_process_flexslider_views()
 */
function parrot_splash_image_process_flexslider(&$vars) {
  $module_path = drupal_get_path('module', 'parrot_splash_image');
  drupal_add_js($module_path . '/js/parrot_splash_image.min.js', array('type' => 'file', 'scope' => 'footer', 'weight' => 1000));
}